[build]
  command = "cd frontend && npm install && npm run build"
  functions = "netlify/functions"
  publish = "frontend/dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- frontend "

