# example netlify.toml
[build]
  command = "cd frontEnd && npm install && npm run build"
  functions = "netlify/functions"
  publish = "frontEnd/dist"

[build.ignore]
  # Ignore everything except the frontend directory
  files = ["/*", "!/frontend/**/*"]
