[build]
builder = "nixpacks"
watchPatterns = ["backEnd/**"]
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"
rootDirectory = "backEnd"